version: "3.1"

services:
  # Serviço que irá rodar o node
  api:
    build: ./backend
    container_name: setup_api
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env

  # Serviço que irá rodar o banco de dados
  db:
    container_name: setup_db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
